<a href="https://colab.research.google.com/github/ilinthm26/Gender-Inclusivity-and-Pay-Gap-Analysis/blob/main/IBM_Gender_Inclusivity_and_Pay_Gap_Data_Understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Gender Inclusivity and Pay Gap Analysis***

Sections:

Import Libraries

Load Dataset

Initial Data Inspection

Missing Values Check and Solve

Data Standardization

Feature Engineering

  Age Bands

  Tenure Bands
  
  Leadership Flags

# Import Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [4]:
df=pd.read_csv(r'/content/IBM HR Employee Attrition Data.csv')
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

# Initial Data Inspection

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

Drop constant and irrelevant columns for the analysis.

In [6]:
df.drop(columns=['Over18','DistanceFromHome','EmployeeCount','MaritalStatus','RelationshipSatisfaction','StockOptionLevel','TrainingTimesLastYear'],inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1470 non-null   int64
 1   Attrition                1470 non-null   object
 2   BusinessTravel           1470 non-null   object
 3   DailyRate                1470 non-null   int64
 4   Department               1470 non-null   object
 5   Education                1470 non-null   int64
 6   EducationField           1470 non-null   object
 7   EmployeeNumber           1470 non-null   int64
 8   EnvironmentSatisfaction  1470 non-null   int64
 9   Gender                   1470 non-null   object
 10  HourlyRate               1470 non-null   int64
 11  JobInvolvement           1470 non-null   int64
 12  JobLevel                 1470 non-null   int64
 13  JobRole                  1470 non-null   object
 14  JobSatisfaction          1470 non-null   int64
 15  MonthlyIncome            1470 non-null   int64
 16  MonthlyRate              1470 non-null   int64
 17  NumCompaniesWorked       1470 non-null   int64
 18  OverTime                 1470 non-null   object
 19  PercentSalaryHike        1470 non-null   int64
 20  PerformanceRating        1470 non-null   int64
 21  StandardHours            1470 non-null   int64
 22  TotalWorkingYears        1470 non-null   int64
 23  WorkLifeBalance          1470 non-null   int64
 24  YearsAtCompany           1470 non-null   int64
 25  YearsInCurrentRole       1470 non-null   int64
 26  YearsSinceLastPromotion  1470 non-null   int64
 27  YearsWithCurrManager     1470 non-null   int64
dtypes: int64(21), object(7)
memory usage: 321.7+ KB

In [7]:
df.describe()

,Age,DailyRate,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,StandardHours,TotalWorkingYears,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,2.912925,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,6502.931293,...,2.693197,15.209524,3.153741,80.0,11.279592,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,1.024165,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,4707.956783,...,2.498009,3.659938,0.360824,0.0,7.780782,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,...,0.000000,11.000000,3.000000,80.0,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,2911.000000,...,1.000000,12.000000,3.000000,80.0,6.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,3.000000,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,4919.000000,...,2.000000,14.000000,3.000000,80.0,10.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,4.000000,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,8379.000000,...,4.000000,18.000000,3.000000,80.0,15.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,5.000000,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,...,9.000000,25.000000,4.000000,80.0,40.000000,4.000000,40.000000,18.000000,15.000000,17.000000

# Missing Values Check and Solve

No missing values found. Data is clean

In [8]:
df.isna().sum()

Age                        0
Attrition                  0
BusinessTravel             0
DailyRate                  0
Department                 0
Education                  0
EducationField             0
EmployeeNumber             0
EnvironmentSatisfaction    0
Gender                     0
HourlyRate                 0
JobInvolvement             0
JobLevel                   0
JobRole                    0
JobSatisfaction            0
MonthlyIncome              0
MonthlyRate                0
NumCompaniesWorked         0
OverTime                   0
PercentSalaryHike          0
PerformanceRating          0
StandardHours              0
TotalWorkingYears          0
WorkLifeBalance            0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

# Data Standardization

This is to check if the categorical values in the dataset is in a standardized format. If not standardized: KPIs become inaccurate, groupby operations break, dashboard filters duplicates category.

All the columns are in standardized format.

In [9]:
for col in df.select_dtypes(['object']):
  print('------------',col,'------------')
  print(df[col].unique())
  print()

------------ Attrition ------------
['Yes' 'No']

------------ BusinessTravel ------------
['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']

------------ Department ------------
['Sales' 'Research & Development' 'Human Resources']

------------ EducationField ------------
['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']

------------ Gender ------------
['Female' 'Male']

------------ JobRole ------------
['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']

------------ OverTime ------------
['Yes' 'No']

# Feature Engineering

For HR D&I analytics, the most important engineered features are:

Age Bands

Tenure Bands

Leadership Flag

## Age Bands

In [10]:
df['Age'].describe() # range from 18-60

count    1470.000000
mean       36.923810
std         9.135373
min        18.000000
25%        30.000000
50%        36.000000
75%        43.000000
max        60.000000
Name: Age, dtype: float64


Age Bands helps in:

Diversity analysis,

Attrition trend analysis

Leadership *Maturity*

In [11]:
age_bins=[18,25,35,45,55,65]
age_labels=['18-25','26-35','36-45','46-55','56-65']
df['AgeBand']=pd.cut(
    df['Age'],
    bins=age_bins,
    labels=age_labels,
    right=False
)

Most of the employees,i.e., 37% are aged between 26-35. Followed by 34% between 36-45.

In [34]:
df['AgeBand'].unique()

['36-45', '46-55', '26-35', '56-65', '18-25']
Categories (5, object): ['18-25' < '26-35' < '36-45' < '46-55' < '56-65']

In [12]:
df['AgeBand'].value_counts(normalize=True)*100

AgeBand
26-35    37.687075
36-45    34.353741
46-55    16.666667
18-25     6.598639
56-65     4.693878
Name: proportion, dtype: float64

## Tenure Bands

In [13]:
df['TotalWorkingYears'].describe() # range from 0 to 40

count    1470.000000
mean       11.279592
std         7.780782
min         0.000000
25%         6.000000
50%        10.000000
75%        15.000000
max        40.000000
Name: TotalWorkingYears, dtype: float64

Tenure bands helps in analysing:

Are new hires leaving more?

Is leadership dominated by long-term employess?

Where is promotion stagation happening?

In [28]:
tenure_bins=[0,2,5,10,20,40]
tenure_labels=['0-2 Years','3-5 Years','6-10 Years','11-20 Years','21-40 Years']

df['TenureBand']=pd.cut(
    df['YearsAtCompany'],
    bins=tenure_bins,
    labels=tenure_labels,
    right=True,
    include_lowest=True
)

31% of employees are with the company for last 10 years. We observe a decreasing percentage of employees in the longer tenure bands, with only 4.6% having 21-40 years of service. This could indicate a younger company, natural retirement rates, or potentially higher turnover in earlier career stages.

In [29]:
df['TenureBand'].unique()

['6-10 Years', '0-2 Years', '3-5 Years', '21-40 Years', '11-20 Years']
Categories (5, object): ['0-2 Years' < '3-5 Years' < '6-10 Years' < '11-20 Years' < '21-40 Years']

In [30]:
df['TenureBand'].value_counts(normalize=True)*100

TenureBand
6-10 Years     30.476190
3-5 Years      29.523810
0-2 Years      23.265306
11-20 Years    12.244898
21-40 Years     4.489796
Name: proportion, dtype: float64

## Leadership Flags

In [31]:
df['JobRole'].unique()

array(['Sales Executive', 'Research Scientist', 'Laboratory Technician',
       'Manufacturing Director', 'Healthcare Representative', 'Manager',
       'Sales Representative', 'Research Director', 'Human Resources'],
      dtype=object)

Leadership roles involved in the company are 'Manager',
    'Manufacturing Director',
    'Research Director' .
 22% of the employees are performing manager role in the organization.

In [32]:
leadershipRoles=[
    'Manager',
    'Manufacturing Director',
    'Research Director'
 ]

df['IsLeader']=df['JobRole'].isin(leadershipRoles).astype(int)
df['IsLeader'].mean()

np.float64(0.22244897959183674)

Feature engineering was performed to create structured workforce segments:

Age_Band enables demographic diversity analysis

Tenure_Band enables retention lifecycle analysis

Is_Leader simplifies leadership representation metrics

In [35]:
df.to_csv(r'processed_hr_data.csv', index=False)